### PR TITLE
remove surrounding ticks from input

### PR DESCRIPTION
**Pull request by kRITZCREEK**
temporary (!) fix for emacs windows problems

### CODE REVIEW

**Comment by kRITZCREEK** [comment]
@bsermons @user471 could you give this a try? Should fix https://github.com/epost/psc-ide-emacs/issues/31 for now

**Comment by user471** [comment]
I cannot build it. Could you release binaries?

**Comment by kRITZCREEK** [comment]
I'll leave to travel around for the weekend^^ So your earliest bet is monday in that case. Building is as simple as downloading haskell-stack and running stack setup && stack install inside the checked out psc-ide repo though.

**Comment by bsermons** [comment]
I had to remove the space between the last tick and the pipe operator in elisp but after that it works.  Thanks for going ahead and making this change until a better solution comes around.

**Comment by kRITZCREEK** [comment]
Allright @bsermons thanks for testing this ;)

**Pull request merged**
