### PR TITLE
Case split

### PR DESCRIPTION
**Pull request by kRITZCREEK**

### CODE REVIEW

**Comment by kRITZCREEK** [comment]
@nwolverson @FrigoEU @epost What do you think? Would you like to lift the API for the casesplit on a more semantic level? Right now it's pretty much just string replacement but it worked out pretty fine for a prototypical emacs implementation. 

Not sure if you've seen the gif but here is the command in action:

case-split

**Comment by nwolverson** [comment]
Without actually trying to implement, looks reasonable as it is.

**Comment by FrigoEU** [comment]
I'm on vacation, so only just now saw this...

Having the user type in the type that they want split by the command is one way, but it would be much nicer if we could deduce it automatically from the function's type signature. Do you see this as something the editor should do? 

I checked Idris, and there it seems the compiler does it. There you just pass in the line, and the variable you want to split, and the case split command figures everything out. I have no idea how hard it would be to implement this, but I do think this is more powerful than what is available in psc-ide atm. Not to take away from your work though, it's completely usable as it is now!

**Comment by kRITZCREEK** [comment]
@FrigoEU that's totally planned^^ I'm working on it. I'll start by using eventually supplied type parameters to properly type the splits:

```purescript
x :: Maybe Int
(Just (_ :: Int)
Nothing
```
(Right now you'd get `(Just (_ :: a))`)

As long as we keep the "explicitly" typed splits we could use that information for further splitting and then provide a command to clean up the type annotations once you're done.
For the "real" Idris experience I'll need to get more comfy with the compiler...

**Pull request merged**
