### PR TITLE
[WIP] adds functions to filter Completions by Modules

### PR DESCRIPTION
**Pull request by kRITZCREEK**

### CODE REVIEW

**Comment by kRITZCREEK** [comment]
@epost Could you try this out? 

The new Syntax for completions:

```
complete prefix (File | Project | Pursuit) using Data.Array, Data.Map, Your.Module.Name
```

the using clause is optional.

This also changes the way completions are represented to `(ModuleIdent, Ident, Type)`. How to format that for easy consumption of the editor plugins is of course open for discussion.

**Comment by epost** [comment]
Sure, I'll have a look now.

On Wed, Sep 9, 2015 at 5:25 PM, Christoph Hegemann <notifications@github.com

**Comment by kRITZCREEK** [comment]
@nwolverson Maybe you want to chime in aswell? I just tried out your changes in the Atom plugin. It's amazing! I'm having so much fun with it :dancers:

If you've got any thoughts on how to format the results of completion I would like to hear them.

**Comment by epost** [comment]
Bah, I have a flaky internet connection today. :( This may take a while.

**Comment by nwolverson** [comment]
Just to clarify what that means (can't try it just now)
  * No using clause => No filter
  * Otherwise filters completions to things directly contained in the listed modules? 

Not sure what "help the editors" means. Does it mean an operation to get the imports list of the file in a format suitable for passing back into the filter above?

The use case I imagine is in a given file, get all completions including all of its imports. I guess the thinking is you have loaded all (direct) dependencies from the project as a whole, and then filter them to the particular file?

When it comes to including the types already, that's great.

**Comment by kRITZCREEK** [comment]
Yes that is how the using clause works.

And yes that is the intended use-case. Since when you're switching between multiple files in a project you might want to only autocomplete things in scope in that File.

The format for the suggestions from psc-ide after this PR is:

```
echo "complete filter Project" | psc-ide
(Data.Array, filterM, forall a m. (Prelude.Monad m) => (a -> m Prim.Boolean) -> Prim.Array a -> m (Prim.Array a)), (Data.Array, filter, forall a. (a -> Prim.Boolean) -> Prim.Array a -> Prim.Array a)
```

This will of course break your plugins, but should also yield some nice benefits.

**Comment by kRITZCREEK** [comment]
I'll merge it. @epost if there is anything you want to change we can talk about that later anyway ;)

**Comment by nwolverson** [comment]
Actually seems like that could be annoying to parse  with both `()` and `,` appearing in PureScript types as well as the transfer format, easier to switch it..?

**Comment by kRITZCREEK** [comment]
I'm totally up for suggestions^^ Tell me what format you could work with

**Comment by nwolverson** [comment]
Just anything that is unambiguous to be parseable by a regex, I think `,` would be a  problem with records and even your example above has `()`. How about `[ ; ; ]` ?

**Comment by kRITZCREEK** [comment]
What if I gave you JSON?

**Comment by nwolverson** [comment]
JSON of course is easy from javascript, I guess should be fine for all editor integrations. Probably more sustainable in general than a plaintext protocol as things get more complex?

**Comment by kRITZCREEK** [comment]
I guess it's probably the most accessible format. And since serialization lives at the very edge of and application it would be easy to provide multiple formats. I could hide the JSON output behind a switch and make it the default soonish?

**Pull request merged**
