### PR TITLE
Add 'cwd' command so clients can ask for the project dir

### PR DESCRIPTION
**Pull request by epost**
psc-ide-server has the purescript project dir as its working directory. this command provides it to clients.

### CODE REVIEW

**Comment by epost** [comment]
Drat, this seems to break parsing of 'completion' at least.

**Comment by kRITZCREEK** [comment]
Just change 
```
(string "cwd" >> return Cwd) <|>
```
into
```
try (string "cwd" >> return Cwd) <|>
```

The problem is that `string "cwd"` consumes the `c` from `complete` and can't go back from there unless you allow backtracking with `try`.

**Comment by kRITZCREEK** [comment]
Thank you :+1:

**Comment by epost** [comment]
:+1: and you :)

**Pull request merged**
