### PR TITLE
watches the output directory and reloads on change

### PR DESCRIPTION
**Pull request by kRITZCREEK**
fixes #89

### CODE REVIEW

**Comment by FrigoEU** [comment]
Works like a charm for me. I updated my psc-ide-vim plugin locally so the loading and refreshing etc is optimised, I'll publish it as soon as this is merged. Great work!

**Comment by kRITZCREEK** [comment]
I still have to check if this notices new modules being added. We wouldn't want to require a restart on adding a module. Once that is confirmed I'll merge this in.

**Comment by kRITZCREEK** [comment]
Sigh... So I've played around with this a bit. There are still 2 major issues left:

- New Modules don't get added to the watcher.

  So if you add a new file/module and make changes to it these changes don't get picked up by psc-ide
- Adding an import to a module that has been loaded does not load the new dependency into the 
  server which means that you still have to manually import the new dependency/reload all 
  dependencies for the affected module

The first issue could be handled by restarting the filewatcher whenever a new module is loaded into the server.

For the second issue... We might want to just canonically load all modules that are not "dependencies" into the server.

**Comment by kRITZCREEK** [comment]
I'll merge this in for now, because I believe I need to work on other parts of the codebase a bit to fix the remaining bugs. (Proper Logging, Threading System, Better error handling)

This still improves on the current situation and is a baseline which we can iterate on.

**Pull request merged**
