### PR TITLE
makes the output path configurable

### LINKED ISSUE #94: psc-ide-server: Be able to provide non-default location to "output/" path
It'd be lovely if we could specify the build-output directory; at the moment it's [unfortunately hardcoded](https://github.com/kRITZCREEK/psc-ide/blob/5790093d233f8ff03d94a6d96c2a0333bf50d960/server/Main.hs#L63) to whatever's given to `-d` plus `"output"/`.

(In my case, for example, I'm writing a library that's being built to `lib`, so that I can publish it on npm and have it look like any other library. I'm also working on something else that's building to `support/lib/`.)

PS: Thanks for writing this project. :smile:

### PR DESCRIPTION
**Pull request by kRITZCREEK**
fixes #94

### CODE REVIEW

**Comment by damncabbage** [comment]
Possibly needs this under [Running the Server](https://github.com/kRITZCREEK/psc-ide#running-the-server) in the README:
```
+ `--output-directory`: Specify where to look for compiled output inside your project directory. Defaults to `output/`, relative to either the current directory or the directory specified by `-d`.
```

**Comment by kRITZCREEK** [comment]
Hey thanks! No worries I'll fix that type error and document the new flag. psc-ide is meant to be built with stack. With no version constraints in the .cabal file building with cabal will hardly ever work^^

**Comment by kRITZCREEK** [comment]
@damncabbage I'm at work right now. Could you give this a go?

**Comment by damncabbage** [comment]
:tada: Works for me. :+1:

**Comment by kRITZCREEK** [comment]
Allright thanks for testing!

**Pull request merged**
