### PR TITLE
completion and package lookup from Pursuit

### LINKED ISSUE #69: Look for packages containing a specified identifier
Using Pursuit

### PR DESCRIPTION
**Pull request by kRITZCREEK**
fixes #69

### CODE REVIEW

**Comment by kRITZCREEK** [comment]
@nwolverson @epost Would this help you? This enables completion querying from Pursuit.

You can also look for packages that contain a given identifier. That might be a nice route to add needed packages to the bower.json.

**Comment by epost** [comment]
Ah, this is very cool!

**Comment by kRITZCREEK** [comment]
@nwolverson Thanks for the nice catch! In the case of an error from pursuit it should now return an empty list of results. Does that sound sensible or should we trim trailing dots from searches?

**Comment by nwolverson** [comment]
Either way seems like a good start. Could also trim then filter the result but whatever it's minor compared to server process falling over

**Comment by kRITZCREEK** [comment]
Allright :) I'm removing trailing dots from the queries now. Can you give it one more try? I'll squash and merge when it's working fine for you :)

**Comment by nwolverson** [comment]
Seems to work! :+1:

**Comment by paf31** [comment]
:100:

**Pull request merged**
